"""Markdown export for screening reports."""

from __future__ import annotations

from typing import Any


def to_markdown(report: dict[str, Any]) -> str:
    lines: list[str] = []
    system = report.get("system", {})
    summary = report.get("summary", {})
    prov = report.get("ruleset_provenance", {})

    lines.append(f"# LitmusAI Screening Report — {system.get('name', 'Unknown')}")
    lines.append("")
    lines.append(f"**Ruleset:** {prov.get('display_label', 'unknown')}")
    lines.append(f"**Generated:** {report.get('generated_at', '')}")
    lines.append(f"**Input hash:** `{report.get('input_hash_sha256', '')}`")
    lines.append(f"**Overall verdict:** **{summary.get('overall_verdict', '').upper()}**")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Results by Category")
    lines.append("")
    lines.append("| Category | Verdict | Confidence | Rules Triggered |")
    lines.append("|---|---|---|---|")

    for cat_id, cat in report.get("categories", {}).items():
        verdict = cat.get("verdict", "?").upper()
        confidence = cat.get("confidence", "?")
        rules = ", ".join(cat.get("triggered_rules", [])) or "-"
        lines.append(f"| {cat_id} {cat.get('label', '')} | {verdict} | {confidence} | {rules} |")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Disclaimers")
    lines.append("")
    for disc in report.get("disclaimers", []):
        lines.append(f"- {disc}")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by LitmusAI. Not legal advice. Not a notified body.*")
    lines.append("")

    return "\n".join(lines)
